// <auto-generated />
namespace AirHelp.DAL.Migration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AirCompany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AirCompany));
        
        string IMigrationMetadata.Id
        {
            get { return "201802041826460_AirCompany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
