// <auto-generated />
namespace AirHelp.DAL.Migration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class signitureImage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(signitureImage));
        
        string IMigrationMetadata.Id
        {
            get { return "201801240015096_signitureImage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
